#pragma once

#define SIMPLEKV_VER_MAJOR 1
#define SIMPLEKV_VER_MINOR 0
#define SIMPLEKV_VER_PATCH 0

#define SIMPLEKV_TO_VERSION(major, minor, patch) (major * 10000 + minor * 100 + patch)
#define SIMPLEKV_VERSION SIMPLEKV_TO_VERSION(SIMPLEKV_VER_MAJOR, SIMPLEKV_VER_MINOR, SIMPLEKV_VER_PATCH)