set(SIMPLEKV_HEADERS_DIR "${CMAKE_CURRENT_SOURCE_DIR}/include")
file(GLOB SIMPLEKV_TOP_HEADERS "${SIMPLEKV_HEADERS_DIR}/simplekv/*.h")

set(SIMPLEKV_ALL_HEADERS ${SIMPLEKV_TOP_HEADERS})

source_group("Header Files\\simplekv" FILES ${SIMPLEKV_TOP_HEADERS})